### PR TITLE
Use kubespray reset to quickly remove the kubernetes environment.

### PR DESCRIPTION
**Pull request by jjmengze**
So I modified bin / kubespray, added reset related programs.
Added reset.py as the module for reset.

I tested in my cluster, five nodes which are three master nodes and two worker nodes.
The test environment is ubuntu 16.04 & Kubernetes v1.7.3+coreos.0

At the same time I have another test environment

three nodes which are one master nodes and two worker nodes.
The test environment is centos7 & Kubernetes v1.7.3+coreos.0

### CODE REVIEW

**Comment by MengZn** [comment]
@Smana Should I provide detail info of my test environment ?

**Comment by MengZn** [comment]
This is a simple all in one environment this is created by  kubespray cli .

`
kubespray deploy --verbose -u root -k ~/.ssh/id_rsa -n calico
META: ran handlers
META: ran handlers
 ____________
< PLAY RECAP >
 ------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

localhost                  : ok=3    changed=1    unreachable=0    failed=0
master1                    : ok=437  changed=113  unreachable=0    failed=0

Kubernetes deployed successfuly
`

**Comment by MengZn** [comment]
I can get node  info by this command.

```
kubectl get no -o wide
NAME      STATUS    AGE       VERSION           EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION
master1   Ready     1h        v1.7.3+coreos.0   <none>        Ubuntu 16.04.2 LTS   4.4.0-83-generic

```

**Comment by MengZn** [comment]
Then I use this command clean this cluster.
```
kubespray reset -k ~/.ssh/id_rsa
Identity added: /root/.ssh/id_rsa (/root/.ssh/id_rsa)
 __________________________
< CHECKING SSH CONNECTIONS >
 --------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

/home/vagrant/env/bin/ansible --ssh-extra-args -o StrictHostKeyChecking=no -u root -b --become-user=root -m ping all -i /root/.kubespray/inventory/inventory.cfg
master1 | SUCCESS => {
    "changed": false,
    "ping": "pong"
}
All hosts are reachable
Reset kubernetes cluster with the above command ? [Y/n] y
 ____________________
< RUN Reset PLAYBOOK >
 --------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

 ____________
< PLAY [all] >
 ------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

 ________________________
< TASK [Gathering Facts] >
 ------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

ok: [master1]
 ___________________________
< TASK [check confirmation] >
 ---------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

skipping: [master1]
 ________________________________________________
< TASK [kubespray-defaults : Configure defaults] >
 ------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

ok: [master1] => {
    "msg": "Check roles/kubespray-defaults/defaults/main.yml"
}
 ______________________________________
< TASK [reset : reset | stop services] >
 --------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

changed: [master1] => (item=kubelet)
changed: [master1] => (item=etcd)
 ________________________________________
< TASK [reset : reset | remove services] >
 ----------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

changed: [master1] => (item=kubelet)
changed: [master1] => (item=etcd)
ok: [master1] => (item=vault)
ok: [master1] => (item=calico-node)
 ______________________________________________
< TASK [reset : reset | remove docker dropins] >
 ----------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

changed: [master1] => (item=docker-dns.conf)
changed: [master1] => (item=docker-options.conf)
 ________________________________________________
< TASK [reset : reset | systemctl daemon-reload] >
 ------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

changed: [master1]
 ______________________________________________
< TASK [reset : reset | remove all containers] >
 ----------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

changed: [master1]
 _________________________________________________
< TASK [reset : reset | restart docker if needed] >
 -------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

changed: [master1]
 ____________________________________________________
< TASK [reset : reset | gather mounted kubelet dirs] >
 ----------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

 [WARNING]: Consider using mount module rather than running mount

changed: [master1]
 _____________________________________________
< TASK [reset : reset | unmount kubelet dirs] >
 ---------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

changed: [master1] => (item=/var/lib/kubelet/pods/eed99120-92c4-11e7-b2c7-080027c6913f/volumes/kubernetes.io~secret/default-token-jz5xn)
changed: [master1] => (item=/var/lib/kubelet/pods/ee1ec6e2-92c4-11e7-b2c7-080027c6913f/volumes/kubernetes.io~secret/default-token-jz5xn)
changed: [master1] => (item=/var/lib/kubelet/pods/ece0af04-92c4-11e7-b2c7-080027c6913f/volumes/kubernetes.io~secret/default-token-jz5xn)
changed: [master1] => (item=/var/lib/kubelet/pods/dfc92552-92c4-11e7-b2c7-080027c6913f/volumes/kubernetes.io~secret/default-token-jz5xn)
 _______________________________
< TASK [reset : flush iptables] >
 -------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

changed: [master1]
 __________________________________________________________
< TASK [reset : reset | delete some files and directories] >
 ----------------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

changed: [master1] => (item=/etc/kubernetes)
changed: [master1] => (item=/var/lib/kubelet)
changed: [master1] => (item=/var/lib/etcd)
changed: [master1] => (item=/etc/ssl/etcd)
ok: [master1] => (item=/var/log/calico)
changed: [master1] => (item=/etc/cni)
ok: [master1] => (item=/etc/nginx)
ok: [master1] => (item=/etc/dnsmasq.d)
ok: [master1] => (item=/etc/dnsmasq.conf)
ok: [master1] => (item=/etc/dnsmasq.d-available)
changed: [master1] => (item=/etc/etcd.env)
changed: [master1] => (item=/etc/calico)
ok: [master1] => (item=/etc/weave.env)
changed: [master1] => (item=/opt/cni)
ok: [master1] => (item=/etc/dhcp/dhclient.d/zdnsupdate.sh)
ok: [master1] => (item=/etc/dhcp/dhclient-exit-hooks.d/zdnsupdate)
ok: [master1] => (item=/run/flannel)
ok: [master1] => (item=/etc/flannel)
changed: [master1] => (item=/run/kubernetes)
changed: [master1] => (item=/usr/local/share/ca-certificates/etcd-ca.crt)
changed: [master1] => (item=/usr/local/share/ca-certificates/kube-ca.crt)
ok: [master1] => (item=/usr/local/share/ca-certificates/vault-ca.crt)
changed: [master1] => (item=/etc/ssl/certs/etcd-ca.pem)
changed: [master1] => (item=/etc/ssl/certs/kube-ca.pem)
ok: [master1] => (item=/etc/ssl/certs/vault-ca.crt)
ok: [master1] => (item=/etc/pki/ca-trust/source/anchors/etcd-ca.crt)
ok: [master1] => (item=/etc/pki/ca-trust/source/anchors/kube-ca.crt)
ok: [master1] => (item=/etc/pki/ca-trust/source/anchors/vault-ca.crt)
ok: [master1] => (item=/etc/vault)
changed: [master1] => (item=/var/log/pods/)
changed: [master1] => (item=/usr/local/bin/kubelet)
changed: [master1] => (item=/usr/local/bin/etcd-scripts)
changed: [master1] => (item=/usr/local/bin/etcd)
changed: [master1] => (item=/usr/local/bin/etcdctl)
changed: [master1] => (item=/usr/local/bin/kubernetes-scripts)
changed: [master1] => (item=/usr/local/bin/kubectl)
ok: [master1] => (item=/usr/local/bin/helm)
changed: [master1] => (item=/usr/local/bin/calicoctl)
ok: [master1] => (item=/usr/local/bin/weave)
 ________________________________________________
/ TASK [reset : reset | remove dns settings from \
\ dhclient.conf]                                 /
 ------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

ok: [master1] => (item=/etc/dhclient.conf)
ok: [master1] => (item=/etc/dhcp/dhclient.conf)
 ____________________________________________________________
< TASK [reset : reset | remove host entries from /etc/hosts] >
 ------------------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

changed: [master1]
 ________________________________________
< TASK [reset : reset | Restart network] >
 ----------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

changed: [master1]
 ____________
< PLAY RECAP >
 ------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

master1                    : ok=15   changed=12   unreachable=0    failed=0

Kubernetes Reset successfuly
```

**Comment by MengZn** [comment]
My environment looks like this:
```
cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

**Comment by jjmengze** [comment]
@Smana  Is not this a solution?

**Pull request closed without merging**
