### PR TITLE
[kargo-cli] Add argparse for CentOS deployments

### PR DESCRIPTION
**Pull request by jbunce**
Ansible playbooks for bootstraping Kubernetes hosts are supported in Kargo, but the CLI argument is not present in kargo-cli. This PR adds support for that platform. Tested today with a k8s 1.6.4 build on CentOS 7.

kargo deploy --centos -n calico -u --kube-network 10.200.0.0/16

https://pastebin.com/tB9GevqK

### CODE REVIEW

**Comment by Smana** [comment]
Thank you :+1:

**Comment by Smana** [comment]
However the option is not used.
For example, boostrap for ubuntu and cores is used in src/kargo/deploy.py

```
        # Bootstrap                                 
        if 'coreos' in self.options.keys() and self.options['coreos']:                                   
            cmd = cmd + ['-e', 'bootstrap_os=coreos']                                                    
        elif 'ubuntu' in self.options.keys() and self.options['ubuntu']:                                 
            cmd = cmd + ['-e', 'bootstrap_os=ubuntu'] 
```

**Comment by buncej** [comment]
Good spot! Updated commit and I've got RH/CentOS specific plays executing: https://pastebin.com/7Qhf0E4L

**Comment by Smana** [comment]
Could you please rebase on master, sorry for the delay

**Pull request merged**
